import type { AiAgent, Asset, Project, TeamMember } from "@/lib/types";

export const organization = {
  name: "Foster + Partners Studio",
  slug: "foster-partners",
  plan: "Enterprise",
  type: "Architecture + Interior",
  aiBudget: 18000,
  aiSpend: 9420,
  health: 94,
};

export const dashboardStats = [
  { label: "Active Projects", value: "42", delta: "+8%", tone: "positive" },
  { label: "Pipeline", value: "$18.4M", delta: "+14%", tone: "positive" },
  { label: "Team Utilization", value: "84%", delta: "-3%", tone: "warning" },
  { label: "AI Time Saved", value: "712h", delta: "+22%", tone: "positive" },
];

export const revenueSeries = [
  { month: "Jan", revenue: 1.8, forecast: 2.1 },
  { month: "Feb", revenue: 2.4, forecast: 2.2 },
  { month: "Mar", revenue: 2.1, forecast: 2.6 },
  { month: "Apr", revenue: 3.2, forecast: 3.1 },
  { month: "May", revenue: 3.7, forecast: 3.6 },
  { month: "Jun", revenue: 4.3, forecast: 4.8 },
];

export const utilizationSeries = [
  { department: "Architecture", utilization: 88, capacity: 95 },
  { department: "Interiors", utilization: 82, capacity: 90 },
  { department: "Brand", utilization: 68, capacity: 80 },
  { department: "Production", utilization: 93, capacity: 96 },
  { department: "Strategy", utilization: 74, capacity: 82 },
];

export const projects: Project[] = [
  {
    id: "prj_atlas",
    code: "A-2408",
    name: "Atlas Financial HQ",
    client: "Atlas Financial Group",
    type: "Architecture commission",
    location: "London, UK",
    phase: "Design Dev",
    status: "At Risk",
    lead: "Mira Chen",
    budget: 4800000,
    spent: 3160000,
    margin: 28,
    completion: 58,
    dueInDays: 18,
    risk: "Facade consultant dependency moved critical path by 6 days.",
    cover: "structural atrium and trading floor concept",
  },
  {
    id: "prj_nova",
    code: "I-1182",
    name: "Nova Labs Workplace",
    client: "Nova Therapeutics",
    type: "Interior fit-out",
    location: "Boston, US",
    phase: "Documentation",
    status: "On Track",
    lead: "Ishaan Kapoor",
    budget: 1320000,
    spent: 790000,
    margin: 34,
    completion: 74,
    dueInDays: 9,
    risk: "Millwork package approved; lighting revision pending.",
    cover: "biophilic lab workplace with modular collaboration rooms",
  },
  {
    id: "prj_sora",
    code: "B-0720",
    name: "Sora Identity System",
    client: "Sora Hotels",
    type: "Brand identity",
    location: "Singapore",
    phase: "Schematic",
    status: "Review",
    lead: "Elena Rossi",
    budget: 640000,
    spent: 280000,
    margin: 41,
    completion: 44,
    dueInDays: 27,
    risk: "Client board review scheduled with two naming territories.",
    cover: "luxury hospitality brand world with tactile print system",
  },
  {
    id: "prj_meridian",
    code: "P-5301",
    name: "Meridian Expo Pavilion",
    client: "Meridian Mobility",
    type: "Production job",
    location: "Dubai, UAE",
    phase: "Construction",
    status: "Blocked",
    lead: "Theo Grant",
    budget: 920000,
    spent: 811000,
    margin: 12,
    completion: 81,
    dueInDays: 5,
    risk: "AV supplier requires revised electrical load confirmation.",
    cover: "kinetic product pavilion with suspended media canopy",
  },
];

export const team: TeamMember[] = [
  {
    id: "tm_mira",
    name: "Mira Chen",
    role: "Design Director",
    department: "Architecture",
    location: "London",
    capacity: 40,
    utilization: 92,
    availability: "Overallocated",
    skills: ["BIM", "Urban design", "Client strategy"],
  },
  {
    id: "tm_ishaan",
    name: "Ishaan Kapoor",
    role: "Interior Lead",
    department: "Interiors",
    location: "Bangalore",
    capacity: 40,
    utilization: 78,
    availability: "Focused",
    skills: ["FF&E", "Workplace", "Material systems"],
  },
  {
    id: "tm_elena",
    name: "Elena Rossi",
    role: "Brand Strategy Lead",
    department: "Brand",
    location: "Milan",
    capacity: 36,
    utilization: 64,
    availability: "Available",
    skills: ["Identity", "Editorial", "Campaigns"],
  },
  {
    id: "tm_theo",
    name: "Theo Grant",
    role: "Production Manager",
    department: "Production",
    location: "Dubai",
    capacity: 45,
    utilization: 97,
    availability: "Overallocated",
    skills: ["Print", "Installations", "Vendor control"],
  },
];

export const assets: Asset[] = [
  {
    id: "ast_001",
    name: "Atlas HQ facade study R12.pdf",
    type: "Drawing",
    project: "Atlas Financial HQ",
    version: "v12",
    status: "Review",
    tags: ["facade", "atrium", "planning"],
    updated: "18 minutes ago",
  },
  {
    id: "ast_002",
    name: "Nova Labs finish schedule.xlsx",
    type: "Schedule",
    project: "Nova Labs Workplace",
    version: "v8",
    status: "Approved",
    tags: ["materials", "interiors", "cost"],
    updated: "1 hour ago",
  },
  {
    id: "ast_003",
    name: "Sora brand territory deck.pptx",
    type: "Presentation",
    project: "Sora Identity System",
    version: "v4",
    status: "Published",
    tags: ["brand", "client-ready", "strategy"],
    updated: "Yesterday",
  },
  {
    id: "ast_004",
    name: "Meridian pre-press checklist.docx",
    type: "Checklist",
    project: "Meridian Expo Pavilion",
    version: "v3",
    status: "Draft",
    tags: ["production", "supplier", "QA"],
    updated: "2 days ago",
  },
];

export const aiAgents: AiAgent[] = [
  {
    id: "agent_budget",
    name: "Budget Guardian",
    cadence: "Every 4 hours",
    status: "Watching",
    lastRun: "12 minutes ago",
    spend: 126,
    signal: "Meridian projected to exceed approved contingency by 4.8%.",
  },
  {
    id: "agent_deadline",
    name: "Deadline Sentinel",
    cadence: "Realtime",
    status: "Running",
    lastRun: "Live",
    spend: 88,
    signal: "Atlas facade dependency may affect client board date.",
  },
  {
    id: "agent_report",
    name: "Report Writer",
    cadence: "Friday 16:00",
    status: "Watching",
    lastRun: "3 days ago",
    spend: 242,
    signal: "Weekly executive report draft is 68% prepared.",
  },
  {
    id: "agent_curator",
    name: "Knowledge Curator",
    cadence: "Nightly",
    status: "Paused",
    lastRun: "Yesterday",
    spend: 54,
    signal: "2,418 chunks indexed across drawings and meeting notes.",
  },
];

export const notifications = [
  "Client approved Nova Labs millwork package.",
  "AI extracted 14 risks from Atlas planning comments.",
  "Stripe received Sora Hotels milestone payment.",
  "Meridian RFI #18 requires director approval.",
];
